<?php

$lang['QrcodeTitle'] = 'QRcode styles modify the description -'; // QRcode樣式修改說明 -
$lang['Project'] = 'project'; // 項目
$lang['Explanation'] = 'Explanation'; // 說明
$lang['Exp_1'] = 'QRcode Chiduo from 100px - adjusted 450px, you can see the change by adjusting the size of the entire QRcode.'; // QRcode尺吋可以從 100px - 450px 進行調整，您可以透過調整看到整個QRcode大小的改變。
$lang['Exp_2'] = 'Foreground color is the original color of the common QRcode black spots, you can change into other colors, we recommend that you use dark, and background color with a high contrast, high contrast colors, for example, (foreground: black Background: white.'; //前景顏色，就是原本常見的QRcode黑點顏色，您可以變更成其他顏色，建議您使用深色，並與背景顏色具有高反差、高對比的顏色，比如說(前景：黑色，背景：白色。
$lang['Exp_3'] = 'Background color is the original common QRcode white background color, you can change into other colors, it is recommended that you use a white or very light color, can not easily be avoided QRcode scan read.'; // 背景顏色，就是原本常見的QRcode白底背景顏色，您可以變更成其他顏色，建議您使用白色或極淺顏色，避免QRcode不易被掃描讀取。
$lang['Exp_4'] = 'Level of detail, you can start with adjustments to observe the change to understand the role of this degree of difference between the number of pixels that amount, the lower the degree of use of the same data can be used on behalf of the fewer number of pixels to represent you from 1 - 10 to adjust, Although fewer points QRcode more concise and clean, but it is recommended that you scan test to see if the scan is not easy, thereby fine-tune the most appropriate level of detail.'; // 細緻程度，您可以先由調整來觀察變化去了解作用，此程度差異在於像素點數量多寡，使用程度越低代表同等資料可以用越少的像素數量去表示，您可以由 1 - 10 去調整，點數越少雖然QRcode較為簡明乾淨，但建議您掃描測試，看是否不容易被掃描，藉此微調最適合的細緻程度。
$lang['Exp_5'] = 'P. S. Sometimes the data is too large, the level of detail will no longer be able to reduce the number of pixels.'; // P. S. 有時候資料量過大，細緻程度將無法再縮減像素數量。
$lang['Exp_6'] = 'Edge blank, blank is scanned in order to increase the chances of success of, as long as enough to blank the extent appropriate blank can make this QRcode, easier QRcode scanner reads.'; //邊緣留白，留白是為了增加被掃描成功的機率性，留白程度只要夠用即可，適當的留白可以讓此QRcode，更容易被QRcode掃描器讀取。
$lang['Exp_7'] = 'Jagged pixel level, the main purpose is to smooth the edge pixel level, the higher the value, the more pixels round, the main role is beautiful, you can adjust depending on personal preference.'; //像素鋸齒程度，主要用途在於像素點的邊緣圓滑程度，數值越高，像素點越圓，主要作用為美觀，您可以視個人喜好調整。
$lang['Exp_8'] = 'QRcode degree of occlusion, this property mainly when QRcode by some shelter, if you set the text labels, graphics, labels, or external factors, such as dirt, etc., blocking the original QRcode pixels, which may cause QRcode not sweep out of the situation, this attribute is set to 30% meaning that even if your QRcode blocked 30%, or that can be scanned (in theory), but the higher the number of shelter, your QRcode pixel arrangement will be relatively complicated .';// QRcode遮擋程度，這個屬性主要是當QRcode被某些遮蔽物，如您設定的文字標籤、圖形標籤，或外在因素，如髒汙等，擋住的原本QRcode的像素，這些有可能造成QRcode掃不出來的情形，這個屬性設定為30%的意思，即您的QRcode就算被擋住3成，還是能被掃描出來(理論上)，但越高的遮蔽數，您的QRcode像素排佈將相對比較繁雜。
$lang['Exp_9'] = 'Save button, button provides you to directly download download QRcode current QRcode, and he will be present store style editing; if you only need to save the edited QRcode styles, you can use store-style button.';// 儲存按鈕，下載QRcode按鈕提供您直接下載當前QRcode，同時他會一併儲存目前編輯的樣式；如果您只需要儲存編輯好的QRcode樣式，您可以使用儲存樣式按鈕。
$lang['Exp_10'] = 'Label type, this QRcode Editor There are five types of tag, no tag, text labels (banners), text labels, graphics, labels (banners), graphic labels, lets you choose whether to embed text (graphics) tab.';// 標籤類型，本QRcode編輯器共有五種標籤類型，無標籤、文字標籤(橫幅)、文字標籤、圖形標籤(橫幅)、圖形標籤等，供您選擇是否嵌入文字(圖形)標籤。
$lang['Exp_11'] = 'Text label, when you use the text labels (banners) or text labels mode, you can set the tag, for example: my business through the link.';// 文字標籤內容，當您使用了文字標籤(橫幅)，或文字標籤模式，您可以設定標籤內容，例如：我的業務通連結。
$lang['Exp_12'] = 'Font text labels, you can set the text font tag';// 文字標籤字型，您可以設定文字標籤字型
$lang['Exp_13'] = 'Color of text labels, you can set the color of the text label';// 文字標籤顏色，您可以設定文字標籤顏色
$lang['Exp_14'] = 'Select the graphic tag, when you use the graphic labels (banners), or graphic labels, you can upload graphics to be embedded in QRcode, file capacity is limited to 3MB.';// 圖形標籤選擇，當您使用了圖形標籤(橫幅)，或圖形標籤，您可以上傳圖形來嵌入到QRcode中，圖檔容量限制為3MB。
$lang['Exp_15'] = 'Label size, adjust the size of your use of the label, it is recommended not to use too large labels, resulting in QRcode scanning itself is not easily read.';// 標籤尺寸，調整您使用的標籤的大小，建議切勿使用過大標籤，導致QRcode本身不易被掃描讀取。
$lang['Exp_16'] = 'Inline position, you can adjust the position of the label in QRcode move in, it is recommended not to block the QRcode eyes, which makes QRcode "can not" be scanned to read.';// 內嵌位置，您可以調整移動標籤在QRcode中的位置，建議切勿擋住QRcode的眼，這會使QRcode「無法」被掃描讀取。
$lang['Exp_17'] = 'The green box (the top two corners and the lower left corner) for the QRcode\'s "big eyes" blue box (the figure is at the marquee) for the QRcode of "small eyes", I recommend that you do not block the label "big eyes ", and" small eyes "if there is only one, and do not block.';// 圖中綠色框(上方兩角落，以及左下角)為QRcode的「大眼」，藍色框(圖中被框選處)為QRcode的「小眼」，建議您的標籤不要擋住這些「大眼」，而「小眼」若只有一個，也請勿擋住。
$lang['Exp_18'] = 'When you use a higher level of detail, small eyes are relatively large, then you can tolerate a certain, two "small eyes" were shaded.';// 當您使用較高的細緻程度，小眼也相對較多，此時就可以容忍某一、兩個「小眼」被遮蔽。

?>